# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
    defaults:
      run:
        working-directory: BACK-END/API
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: BACK-END/API/package-lock.json
      - run: npm install
      - run: CI=true npm test
    env:
      DBHOST: ${{ secrets.DBHOST }}
      DBNAME: ${{ secrets.DBNAME }}
      DBUSER: ${{ secrets.DBUSER }}
      DBPASSWORD: ${{ secrets.DBPASSWORD }}
      EMAIL: ${{ secrets.EMAIL }}
      PASSWORD: ${{ secrets.PASSWORD }}
      SMTP: ${{ secrets.SMTP }}
      PORTSMTP: ${{ secrets.PORTSMTP }}
      SALAGE: ${{ secrets.SALAGE }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      TEST_MAIL: ${{ secrets.TEST_MAIL }}
      TEST_PASSWORD: ${{ secrets.TEST_PASSWORD }}
